backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: authors
    label: Author
    editor:
      preview: false
    folder: "src/pages/authors"
    create: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "author" } 
      - { label: Name, name: name, widget: string }
      - { label: Image, name: image, widget: image }
  - name: "blog"
    label: "Blog"
    editor:
      preview: false
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - { label: Author, name: author, widget: relation, collection: authors, searchFields: ["name"], valueField: "name" }
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - { label: "Template Key", name: templateKey, widget: hidden, default: index-page }
          - { label: Title, name: title, widget: string }
          - { label: Meta Description, name: metaDescription, widget: text }
          - { label: "Main Pitch Carousel",
              name: mainPitch,
              widget: object,
              fields: [
                { label: Carousel, name: carousel, widget: list,
                  fields: [
                    { label: Image, name: image, widget: image },
                    { label: Title, name: title, widget: string },
                    { label: Body, name: body, widget: markdown }
                  ]
                }
              ]
            }
          - { label: Body, name: body, widget: markdown }
          - { label: Pitches, name: pitches, widget: list,
              fields: [
                { label: Title, name: title, widget: string },
                { label: Body, name: body, widget: markdown },
                { label: Image, name: image, widget: object,
                  fields: [
                    { label: Image, name: image, widget: image },
                    { label: "Alt Text", name: altText, widget: string }
                  ]
                },
                { label: "Link", name: link, widget: object, required: false,
                  fields: [
                    { label: "Link Text", name: text, widget: string, required: false },
                    { label: "Link URL", name: url, widget: string, required: false },
                    { label: "Open in new tab?", name: newTab,widget: boolean, default: false, required: false }
                  ]
                },
                { label: "Video Link", name: videoLink, widget: object, required: false,
                  fields: [
                    { label: "Link Text", name: text, widget: string, required: false },
                    { label: "Link URL", name: url, widget: string, required: false },
                    { label: "Open in new tab?", name: newTab, widget: boolean, default: false, required: false }
                  ]
                }
              ]
            }
      - file: "src/pages/our-workflow/index.md"
        label: "Our Workflow"
        name: our-workflow
        fields:
          - { label: "Template Key", name: templateKey, widget: hidden, default: our-workflow-page }
          - { label: Title, name: title, widget: string }
          - { label: Workflow Items, name: workflows, widget: list,
              fields: [
                { label: Title, name: title, widget: string },
                { label: Description, name: description, widget: text },
                { label: Image, name: image, widget: image },
                { label: Body, name: body, widget: markdown }
              ]
            }
      - file: "src/pages/software/index.md"
        label: Software
        name: software
        fields:
          - { label: "Template Key", name: templateKey, widget: hidden, default: software-page }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Sections, name: sections, widget: list,
              fields: [
                { label: Image, name: image, widget: object,
                  fields: [
                    { label: Image, name: image, widget: image },
                    { label: "Alt Text", name: altText, widget: string }
                  ]
                },
                { label: "Part 1", name: part1, widget: object,
                  fields: [
                    { label: Title, name: title, widget: string },
                    { label: Body, name: body, widget: markdown },
                  ]
                },
                { label: "Part 2", name: part2, widget: object,
                  fields: [
                    { label: Title, name: title, widget: string },
                    { label: Body, name: body, widget: markdown },
                  ]
                },
              ]
            }
      - file: "src/pages/courses/index.md"
        label: "Courses"
        name: courses
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "courses-page"}
          - { label: Title, name: title, widget: string }
          - { label: "Drilling personnel", name: drillingPersonnel, widget: object,
              fields: [
                { label: Title, name: title, widget: string },
                { label: Subtitle, name: subtitle, widget: string },
                { label: Body, name: body, widget: markdown },
                { label: "Action", name: action, widget: object,
                  fields: [
                    { label: "Action Text", name: text, widget: string },
                    { label: "Action URL", name: url, widget: string },
                  ]
                }
              ]
            }
          - { label: "G&G personnel", name: ggPersonnel, widget: object,
              fields: [
                { label: Title, name: title, widget: string },
                { label: Subtitle, name: subtitle, widget: string },
                { label: Body, name: body, widget: markdown },
                { label: "Action", name: action, widget: object,
                  fields: [
                    { label: "Action Text", name: text, widget: string },
                    { label: "Action URL", name: url, widget: string },
                  ]
                }
              ]
            }
          - { label: "Wireline personnel", name: wirelinePersonnel, widget: object,
              fields: [
                { label: Title, name: title, widget: string },
                { label: Subtitle, name: subtitle, widget: string },
                { label: Body, name: body, widget: markdown },
                { label: "Action", name: action, widget: object,
                  fields: [
                    { label: "Action Text", name: text, widget: string },
                    { label: "Action URL", name: url, widget: string },
                  ]
                }
              ]
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Section 1", name: "section1", widget: "object",
              fields: [
                { label: Title, name: title, widget: string },
                { label: Body, name: body, widget: markdown }
              ]
            }
          - { label: "Section 2", name: "section2", widget: "object",
              fields: [
                { label: Title, name: title, widget: string },
                { label: Body, name: body, widget: markdown },
                { label: Countries, name: countries, widget: select, multiple: true,
                  options: [
                    { label: "Afghanistan", value: "AF" },
                    { label: "Albania", value: "AL" },
                    { label: "Algeria", value: "DZ" },
                    { label: "Angola", value: "AO" },
                    { label: "Argentina", value: "AR" },
                    { label: "Armenia", value: "AM" },
                    { label: "Australia", value: "AU" },
                    { label: "Austria", value: "AT" },
                    { label: "Azerbaijan", value: "AZ" },
                    { label: "Bahamas", value: "BS" },
                    { label: "Bangladesh", value: "BD" },
                    { label: "Belarus", value: "BY" },
                    { label: "Belgium", value: "BE" },
                    { label: "Benin", value: "BJ" },
                    { label: "Bhutan", value: "BT" },
                    { label: "Bolivia, Plurinational State of", value: "BO" },
                    { label: "Bosnia and Herzegovina", value: "BA" },
                    { label: "Botswana", value: "BW" },
                    { label: "Brazil", value: "BR" },
                    { label: "Brunei Darussalam", value: "BN" },
                    { label: "Bulgaria", value: "BG" },
                    { label: "Burkina Faso", value: "BF" },
                    { label: "Burundi", value: "BI" },
                    { label: "Cambodia", value: "KH" },
                    { label: "Cameroon", value: "CM" },
                    { label: "Canada", value: "CA" },
                    { label: "Central African Republic", value: "CF" },
                    { label: "Chad", value: "TD" },
                    { label: "Chile", value: "CL" },
                    { label: "China", value: "CN" },
                    { label: "Colombia", value: "CO" },
                    { label: "Congo", value: "CG" },
                    { label: "Congo, the Democratic Republic of the", value: "CD" },
                    { label: "Costa Rica", value: "CR" },
                    { label: "Croatia", value: "HR" },
                    { label: "Cuba", value: "CU" },
                    { label: "Cyprus", value: "CY" },
                    { label: "Czech Republic", value: "CZ" },
                    { label: "Côte d'Ivoire", value: "CI" },
                    { label: "Denmark", value: "DK" },
                    { label: "Djibouti", value: "DJ" },
                    { label: "Dominican Republic", value: "DO" },
                    { label: "Ecuador", value: "EC" },
                    { label: "Egypt", value: "EG" },
                    { label: "El Salvador", value: "SV" },
                    { label: "Equatorial Guinea", value: "GQ" },
                    { label: "Eritrea", value: "ER" },
                    { label: "Estonia", value: "EE" },
                    { label: "Ethiopia", value: "ET" },
                    { label: "Falkland Islands (Malvinas)", value: "FK" },
                    { label: "Fiji", value: "FJ" },
                    { label: "Finland", value: "FI" },
                    { label: "France", value: "FR" },
                    { label: "French Guiana", value: "GF" },
                    { label: "French Southern Territories", value: "TF" },
                    { label: "Gabon", value: "GA" },
                    { label: "Gambia", value: "GM" },
                    { label: "Georgia", value: "GE" },
                    { label: "Germany", value: "DE" },
                    { label: "Ghana", value: "GH" },
                    { label: "Greece", value: "GR" },
                    { label: "Greenland", value: "GL" },
                    { label: "Guatemala", value: "GT" },
                    { label: "Guinea", value: "GN" },
                    { label: "Guinea-Bissau", value: "GW" },
                    { label: "Guyana", value: "GY" },
                    { label: "Haiti", value: "HT" },
                    { label: "Honduras", value: "HN" },
                    { label: "Hungary", value: "HU" },
                    { label: "Iceland", value: "IS" },
                    { label: "India", value: "IN" },
                    { label: "Indonesia", value: "ID" },
                    { label: "Iran, Islamic Republic of", value: "IR" },
                    { label: "Iraq", value: "IQ" },
                    { label: "Ireland", value: "IE" },
                    { label: "Israel", value: "IL" },
                    { label: "Italy", value: "IT" },
                    { label: "Jamaica", value: "JM" },
                    { label: "Japan", value: "JP" },
                    { label: "Jordan", value: "JO" },
                    { label: "Kazakhstan", value: "KZ" },
                    { label: "Kenya", value: "KE" },
                    { label: "Korea, Democratic People's Republic of", value: "KP" },
                    { label: "Korea, Republic of", value: "KR" },
                    { label: "Kuwait", value: "KW" },
                    { label: "Kyrgyzstan", value: "KG" },
                    { label: "Lao People's Democratic Republic", value: "LA" },
                    { label: "Latvia", value: "LV" },
                    { label: "Lebanon", value: "LB" },
                    { label: "Lesotho", value: "LS" },
                    { label: "Liberia", value: "LR" },
                    { label: "Libya", value: "LY" },
                    { label: "Lithuania", value: "LT" },
                    { label: "Luxembourg", value: "LU" },
                    { label: "Macedonia, the former Yugoslav Republic of", value: "MK" },
                    { label: "Madagascar", value: "MG" },
                    { label: "Malawi", value: "MW" },
                    { label: "Malaysia", value: "MY" },
                    { label: "Mali", value: "ML" },
                    { label: "Mauritania", value: "MR" },
                    { label: "Mexico", value: "MX" },
                    { label: "Moldova, Republic of", value: "MD" },
                    { label: "Mongolia", value: "MN" },
                    { label: "Montenegro", value: "ME" },
                    { label: "Morocco", value: "MA" },
                    { label: "Mozambique", value: "MZ" },
                    { label: "Myanmar", value: "MM" },
                    { label: "Namibia", value: "NA" },
                    { label: "Nepal", value: "NP" },
                    { label: "Netherlands", value: "NL" },
                    { label: "New Caledonia", value: "NC" },
                    { label: "New Zealand", value: "NZ" },
                    { label: "Nicaragua", value: "NI" },
                    { label: "Niger", value: "NE" },
                    { label: "Nigeria", value: "NG" },
                    { label: "Norway", value: "NO" },
                    { label: "Oman", value: "OM" },
                    { label: "Pakistan", value: "PK" },
                    { label: "Palestinian Territory, Occupied", value: "PS" },
                    { label: "Panama", value: "PA" },
                    { label: "Papua New Guinea", value: "PG" },
                    { label: "Paraguay", value: "PY" },
                    { label: "Peru", value: "PE" },
                    { label: "Philippines", value: "PH" },
                    { label: "Poland", value: "PL" },
                    { label: "Portugal", value: "PT" },
                    { label: "Puerto Rico", value: "PR" },
                    { label: "Qatar", value: "QA" },
                    { label: "Romania", value: "RO" },
                    { label: "Russian Federation", value: "RU" },
                    { label: "Rwanda", value: "RW" },
                    { label: "Saudi Arabia", value: "SA" },
                    { label: "Senegal", value: "SN" },
                    { label: "Serbia", value: "RS" },
                    { label: "Sierra Leone", value: "SL" },
                    { label: "Slovakia", value: "SK" },
                    { label: "Slovenia", value: "SI" },
                    { label: "Solomon Islands", value: "SB" },
                    { label: "Somalia", value: "SO" },
                    { label: "South Africa", value: "ZA" },
                    { label: "South Georgia and the South Sandwich Islands", value: "GS" },
                    { label: "Spain", value: "ES" },
                    { label: "Sri Lanka", value: "LK" },
                    { label: "Sudan", value: "SD" },
                    { label: "Suriname", value: "SR" },
                    { label: "Swaziland", value: "SZ" },
                    { label: "Sweden", value: "SE" },
                    { label: "Switzerland", value: "CH" },
                    { label: "Syrian Arab Republic", value: "SY" },
                    { label: "Tajikistan", value: "TJ" },
                    { label: "Tanzania, United Republic of", value: "TZ" },
                    { label: "Thailand", value: "TH" },
                    { label: "Timor-Leste", value: "TL" },
                    { label: "Togo", value: "TG" },
                    { label: "Trinidad and Tobago", value: "TT" },
                    { label: "Tunisia", value: "TN" },
                    { label: "Turkey", value: "TR" },
                    { label: "Turkmenistan", value: "TM" },
                    { label: "Uganda", value: "UG" },
                    { label: "Ukraine", value: "UA" },
                    { label: "United Arab Emirates", value: "AE" },
                    { label: "United Kingdom", value: "GB" },
                    { label: "United States", value: "US" },
                    { label: "Uruguay", value: "UY" },
                    { label: "Uzbekistan", value: "UZ" },
                    { label: "Venezuela, Bolivarian Republic of", value: "VE" },
                    { label: "Viet Nam", value: "VN" },
                    { label: "Western Sahara", value: "EH" },
                    { label: "Yemen", value: "YE" },
                    { label: "Zambia", value: "ZM" },
                    { label: "Zimbabwe", value: "ZW" }
                  ]
                }, 
                { label: Experiences, name: experiences, widget: list,
                  fields: [
                    { label: Body, name: body, widget: markdown }
                  ]
                }
              ]
            }
          - { label: "Section 3", name: "section3", widget: "object",
              fields: [
                { label: Title, name: title, widget: string },
                { label: Body, name: body, widget: markdown },
                { label: Image, name: image, widget: object,
                  fields: [
                    { label: Image, name: image, widget: image },
                    { label: "Alt Text", name: altText, widget: string }
                  ]
                },
              ]
            }
      - file: "src/pages/settings/index.md"
        label: Settings
        name: settings
        fields:
          - { label: "Template Key", name: templateKey, widget: hidden, default: settings-page }
          - { label: Contact - interests, name: contactInterests, widget: list,
              fields: [
                { label: "Interest", name: interest, widget: string },
              ]
            }
