backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: authors
    label: Author
    editor:
      preview: false
    folder: "src/pages/authors"
    create: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "author" } 
      - { label: Name, name: name, widget: string }
      - { label: Image, name: image, widget: image }
  - name: "blog"
    label: "Blog"
    editor:
      preview: false
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - { label: Author, name: author, widget: relation, collection: authors, searchFields: ["name"], valueField: "name" }
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: workflowGroups
    label: "Workflow Group"
    editor:
      preview: false
    folder: src/pages/workflowGroups
    create: true
    fields:
      - { label: "Template Key", name: templateKey, widget: hidden, default: "workflow-group" }
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Body, name: body, widget: markdown }
      - { label: Image, name: image, widget: image }

  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - { label: "Template Key", name: templateKey, widget: hidden, default: index-page }
          - { label: Title, name: title, widget: string }
          - { label: "Main Pitch",
              name: mainPitch,
              widget: object,
              fields: [
                { label: Title, name: title, widget: string },
                { label: Body, name: body, widget: markdown },
                { label: Carousel, name: carousel, widget: list,
                  fields: [
                    { label: Image, name: image, widget: image }
                  ]
                },
                { label: "Link", name: link, widget: object,
                  fields: [
                    { label: "Link Text", name: text, widget: string },
                    { label: "Link URL", name: url, widget: string },
                    { label: "Open in new tab?", name: newTab,widget: boolean, default: false }
                  ]
                }
              ]
            }
          - { label: Pitches, name: pitches, widget: list,
              fields: [
                { label: Title, name: title, widget: string },
                { label: Body, name: body, widget: markdown },
                { label: Image, name: image, widget: object,
                  fields: [
                    { label: Image, name: image, widget: image },
                    { label: "Alt Text", name: altText, widget: string }
                  ]
                },
                { label: "Link", name: link, widget: object,
                  fields: [
                    { label: "Link Text", name: text, widget: string },
                    { label: "Link URL", name: url, widget: string },
                    { label: "Open in new tab?", name: newTab,widget: boolean, default: false }
                  ]
                }
              ]
            }
      - file: "src/pages/our-workflow/index.md"
        label: "Our Workflow"
        name: our-workflow
        fields:
          - { label: "Template Key", name: templateKey, widget: hidden, default: our-workflow-page }
          - { label: Title, name: title, widget: string }
          - { label: Workflow Items, name: workflows, widget: list,
              fields: [
                { label: Title, name: title, widget: string },
                { label: Description, name: description, widget: text },
                { label: Image, name: image, widget: image },
                { label: Body, name: body, widget: markdown }
              ]
            }
      - file: "src/pages/software/index.md"
        label: Software
        name: software
        fields:
          - { label: "Template Key", name: templateKey, widget: hidden, default: software-page }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Sections, name: sections, widget: list,
              fields: [
                { label: Image, name: image, widget: object,
                  fields: [
                    { label: Image, name: image, widget: image },
                    { label: "Alt Text", name: altText, widget: string }
                  ]
                },
                { label: "Part 1", name: part1, widget: object,
                  fields: [
                    { label: Title, name: title, widget: string },
                    { label: Body, name: body, widget: markdown },
                  ]
                },
                { label: "Part 2", name: part2, widget: object,
                  fields: [
                    { label: Title, name: title, widget: string },
                    { label: Body, name: body, widget: markdown },
                  ]
                },
              ]
            }
      - file: "src/pages/courses/index.md"
        label: "Courses"
        name: courses
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "courses-page"}
          - { label: Title, name: title, widget: string }
          - { label: "Drilling personnel", name: drillingPersonnel, widget: object,
              fields: [
                { label: Title, name: title, widget: string },
                { label: Subtitle, name: subtitle, widget: string },
                { label: Body, name: body, widget: markdown },
                { label: "Action", name: action, widget: object,
                  fields: [
                    { label: "Action Text", name: text, widget: string },
                    { label: "Action URL", name: url, widget: string },
                  ]
                }
              ]
            }
          - { label: "G&G personnel", name: ggPersonnel, widget: object,
              fields: [
                { label: Title, name: title, widget: string },
                { label: Subtitle, name: subtitle, widget: string },
                { label: Body, name: body, widget: markdown },
                { label: "Action", name: action, widget: object,
                  fields: [
                    { label: "Action Text", name: text, widget: string },
                    { label: "Action URL", name: url, widget: string },
                  ]
                }
              ]
            }
          - { label: "Wireline personnel", name: wirelinePersonnel, widget: object,
              fields: [
                { label: Title, name: title, widget: string },
                { label: Subtitle, name: subtitle, widget: string },
                { label: Body, name: body, widget: markdown },
                { label: "Action", name: action, widget: object,
                  fields: [
                    { label: "Action Text", name: text, widget: string },
                    { label: "Action URL", name: url, widget: string },
                  ]
                }
              ]
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: Image, name: image, widget: image}
