name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - name: log working directory
      run: pwd
    - name: ls all
      run: ls -l
    - name: copy file via ssh 
      uses: garygrossgarten/github-action-scp@release
      with:
          local: /home/runner/work/rigpro.consulting/rigpro.consulting/public
          remote: /var/www/rigpro.consulting
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
