name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - name: log working directory
      run: pwd
    - name: tar public
      run: tar -czvf public.tar.gz ./public
    - name: ls all
      run: ls -l
    - name: copy file via ssh 
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: public.tar.gz
        target: /var/www
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www
          tar -xf public.tar.gz .
          rm -rf rigpro.consulting.bak
          mv rigpro.consulting rigpro.consulting.bak
          mv public rigpro.consulting
          rm public.tar.gz
          ls -al
